import time
def main():
    print("                *")
    print("                *")
    print("               ***")
    print("              *****")
    print("             *******")
    print("            *********")
    print("          *************                A")
    print("             *******")
    print("           ***********                VERY")
    print("         ***************")
    print("       *******************            HAPPY")
    print("           ***********")
    print("         ***************            CHRISTMAS")
    print("       *******************")
    print("     ***********************         AND MY")
    print("         ***************")
    print("       *******************         BEST WISHES")
    print("     ***********************")
    print("   ***************************     FOR THE NEXT")
    print("             ******")
    print("             ******                    YEAR")
    print("             ******")
    time.sleep(100)
main()


